[package]
name = "tatutanatata"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.64"
clap = { version = "4.1.4", features = ["derive", "env"] }
dotenvy = "0.15.6"
futures = "0.3.25"
thirtyfour = "0.31.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.37"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
