[package]
name = "tatutanatata"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
clap = { version = "4.4.15", features = ["derive", "env"] }
dotenvy = "0.15.7"
futures = "0.3.30"
thirtyfour = "0.31.0"
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = { version = "3.0.4", default-features = false }
