---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true

      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: hack
          args: check --workspace --benches --all-features

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-features

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features --all-targets --workspace

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --workspace

      - name: cargo doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --all-features --workspace

      - name: cargo bench
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: --all-features --workspace -- --test
