---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets --workspace -- -D warnings

      - name: cargo build
        run: cargo build --workspace --all-features

      - name: cargo test (with integration tests)
        run: cargo test --all-features --workspace
        if: '(env.TUTANOTA_CLI_USERNAME != null) && (env.TUTANOTA_CLI_PASSWORD != null)'
        env:
          TUTANOTA_CLI_USERNAME: ${{ secrets.TUTANOTA_CLI_USERNAME }}
          TUTANOTA_CLI_PASSWORD: ${{ secrets.TUTANOTA_CLI_PASSWORD }}

      - name: cargo test (NO integration tests)
        run: cargo test --all-features --workspace -- --skip integration
        if: '!((env.TUTANOTA_CLI_USERNAME != null) && (env.TUTANOTA_CLI_PASSWORD != null))'
        env:
          TUTANOTA_CLI_USERNAME: ${{ secrets.TUTANOTA_CLI_USERNAME }}
          TUTANOTA_CLI_PASSWORD: ${{ secrets.TUTANOTA_CLI_PASSWORD }}

      - name: cargo doc
        run: cargo doc --document-private-items --no-deps --all-features --workspace

      - name: cargo bench
        run: cargo bench --profile=dev --all-features --workspace -- --test
