---
name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
    tags:
      - v*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          strict: true

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Geckodriver
        uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Geckodriver
        run: geckodriver &

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-features --all-targets --workspace

      - name: cargo build
        run: cargo build --workspace --all-features

      - name: cargo test
        run: cargo test --all-features --workspace
        env:
          TUTANOTA_CLI_USERNAME: ${{ secrets.TUTANOTA_CLI_USERNAME }}
          TUTANOTA_CLI_PASSWORD: ${{ secrets.TUTANOTA_CLI_PASSWORD }}

      - name: Preserve Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: "*.png"
          if-no-files-found: ignore

      - name: cargo doc
        run: cargo doc --document-private-items --no-deps --all-features --workspace

      - name: cargo bench
        run: cargo bench --profile=dev --all-features --workspace -- --test
